import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Runtime } from '../server/runtime.js';
import { EditorBridge } from '../server/editor.js';
import { liveLayout } from '../live.js';

test('projectless home keys follow foreground app and accept an empty VS Code folder', async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), 'six-empty-'));
  const runtime = new Runtime({ root: null, command: null, requireForeground: true });
  const editor = new EditorBridge(runtime); runtime.editor = editor;
  t.after(async () => { editor.close(); runtime.close(); await rm(root, { recursive: true, force: true }); });
  await runtime.start();
  assert.equal(runtime.context.project, null);
  assert.deepEqual(liveLayout(runtime.context).slice(0, 3).map(key => key.id), ['app_vscode', 'app_codex', 'app_chrome']);
  await runtime.press(4, runtime.context.keyboard.layout_revision);
  assert.equal(runtime.context.keyboard.page, 1);
  assert.equal(liveLayout(runtime.context, 1)[5].id, 'back');
  await runtime.press(5, runtime.context.keyboard.layout_revision);
  assert.equal(runtime.context.keyboard.page, 0);
  runtime.setForeground({ bundle_id: 'com.google.Chrome' });
  assert.equal(runtime.context.keyboard.mode, 'home');
  await assert.rejects(editor.update({ session: 'editor-1', root, state: {} }), /Focus a VS Code/);
  assert.equal(runtime.context.project, null);
  runtime.setForeground({ bundle_id: 'com.microsoft.VSCode' });
  assert.equal(runtime.context.keyboard.mode, 'project');
  assert.equal(liveLayout(runtime.context)[0].disabled, true);
  await assert.rejects(editor.update({ session: 'editor-1', root, state: { focused: false } }), /Focus a VS Code/);
  await editor.update({ session: 'editor-1', root, state: { focused: true, active_file: null, diagnostics: [], agent_terminal_supported: true } });
  assert.equal(runtime.context.project, await (await import('node:fs/promises')).realpath(root));
  assert.equal(runtime.context.git.available, false);
  assert.equal(runtime.context.test_command_available, false);
  assert.equal(liveLayout(runtime.context)[3].id, 'agent_launch');
  await assert.rejects(runtime.runTests(), /No test command/);
  const nextRoot = await mkdtemp(path.join(os.tmpdir(), 'six-next-'));
  t.after(() => rm(nextRoot, { recursive: true, force: true }));
  await editor.update({ session: 'editor-1', root, state: { focused: false } });
  await editor.update({ session: 'editor-2', root: nextRoot, state: { focused: true } });
  assert.equal(runtime.context.project, await (await import('node:fs/promises')).realpath(nextRoot));
});

test('focused Chrome control popup keeps VS Code keys without turning ordinary Chrome into VS Code', () => {
  const runtime = new Runtime({ root: null, command: null });
  runtime.context.vscode = { connected: true, agent_terminal_supported: true };
  runtime.setForeground({ bundle_id: 'com.microsoft.VSCode' });
  assert.equal(runtime.context.keyboard.mode, 'project');
  runtime.setForeground({ bundle_id: 'com.google.Chrome' });
  assert.equal(runtime.context.keyboard.mode, 'home');
  runtime.setPopupFocus({ focused: true });
  assert.equal(runtime.context.keyboard.mode, 'project');
  assert.equal(runtime.context.active_app, 'VS Code via SIX popup');
  runtime.setPopupFocus({ focused: false });
  assert.equal(runtime.context.keyboard.mode, 'home');
  runtime.setForeground({ bundle_id: 'com.microsoft.VSCode' });
  runtime.context.keyboard.mode = 'agent';
  runtime.setPopupFocus({ focused: true });
  runtime.setForeground({ bundle_id: 'com.google.Chrome' });
  assert.equal(runtime.context.keyboard.mode, 'agent');
  runtime.close();
});
